version: "3.4"

services:

  postgres:
    container_name: postgres_url
    image: postgres:15
    volumes:
      - ~/.local/lib/postgresql_url:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: urls
    networks:
      - urlshortener
    ports:
      - "5432:5432"
    
  redis:
    container_name: redis_url
    image: redis:latest
    environment:
      REDIS_PASSWORD: redis
    networks:
      - urlshortener
    ports:
      - "6379:6379"

networks:
  urlshortener:
    driver: bridge
